create table USUARIO
(
	IDUSU VARCHAR2(2)
		constraint USUARIO_PK
			primary key,
	EMLUSU VARCHAR2(30),
	NICKUSU VARCHAR2(30),
	PSSUSU VARCHAR2(32),
	"2FA_CODE" VARCHAR2(10),
	"2FA_EXPIRE_TIME" VARCHAR2(32)
)
/

